### ISSUE TITLE
Update service config

### ISSUE THREAD

**Issue by qdongxu** [wikisio/gitsighup#4]
1. the config file updated as :

```yaml
configsrv:
   endpoint: http://localhost:8080/
services:
  - name: gitsighup
    namespace: dev
    configPath:
      - src: gitsighup.yml
        dst: /opt/gitsighup/conf/
  - name: alertmanager
    namespace: dev
    configPath:
      - src: alertmanager.yml
        dst: /opt/prometheus/alertmanager/conf/
  - name: prometheus
    namespace: dev
    configPath:
      - src: prometheus.yml
        dst: /opt/prometheus/conf/
      - src: alert-rules.yml
        dst: /opt/prometheus/conf/
      - src: rules.yml
        dst: /opt/prometheus/conf

```

3. then run API towards a [go-config-server](https://github.com/gota33/go-config-server)

> GET {cofnigsrv.EndPoint}/{namespace}/{service}/{filename}

to get the configuration file content and save into a temporary dir.  if there're mulitple files, fetch them one by one.

4. compare the file content with 'https://pkg.go.dev/crypto/sha256' , if file changed , copy the file to `dst`.

4. send SIGHUP to the observing service by `systemctl kill --signal HUP \<service_name>
